# Welcome to Jekyll!

########### Global Variables ###########
title: 'Frasco: Jekyll Starter Project'
email: your-email@domain.com
description: >-
  Metrix is a mobile marketing measurement platform that unifies mobile attribution and analytics into one powerful platform.
baseurl: '' # the subpath of your site, e.g. /docs
url: 'https://metrix.ir'
twitter_username: Metrix_ir
github_username: metrixorg
site_name: Metrix
global_vars:
  landing_url: https://metrix.ir
  dashboard_url: https://dashboard.metrix.ir
  blog_url: https://blog.metrix.ir
  docs_url: https://metrix.ir/docs
  site_name: Metrix
  get_demo_url: https://dashboard.metrix.ir/login/demo
  terms_url: https://metrix.ir/terms
  header_logo_alt: Metrix Docs
  contact_email: info@metrix.ir
  footer_logo_alt: Metrix

########### Condfigurations ###########

# Jekyll Configurations: https://jekyllrb.com/docs/configuration/options/
source: src/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-seo-tag
  - jekyll-polyglot
  - jekyll-toc
  - jekyll-minifier

# jekyll-polyglot settings
languages: ['en', 'fa']
default_lang: 'fa'
exclude_from_localizations: ['javascript', 'images', 'css']
parallel_localization: true

# jekyll-minifier settings
jekyll-minifier:
  exclude: 'feed.xml'
  uglifier_args:
    harmony: true

########### Translations ###########
t:
  en:
    nav:
      home: Home
      dashboard: Dashboard
      get_demo: Get a Demo
      blog: Blog
    footer:
      terms: Terms of Service
      contact: Contact Us
      copyright: Designed and Developed by Metrix - Iran
  fa:
    nav:
      home: خانه
      dashboard: داشبورد
      get_demo: دریافت دمو
      blog: وبلاگ
    footer:
      terms: قوانین
      contact: تماس با ما
      copyright: طراحی و توسعه توسط متریکس - ایران
